language: php

php:
  - "5.5"
  - "5.4"

services: mysql

before_install:
  - composer self-update

before_script:
  - composer install --dev
  - mysql -e 'create database cc_testing;'
  - php artisan migrate:install --env=”testing”
 
script:
  - phpunit --configuration phpunit.xml