language: php

php:
  - "5.5"
  - "5.4"

services: mysql

before_install:
  - composer self-update

before_script:
  - composer install --dev --prefer-source --no-interaction
  - mysql -e 'create database cc_testing;'
  - php artisan migrate:install --env="testing"
  - php artisan migrate --env="testing"
  - php artisan serve &
  - sleep 5
 
script:
  - phpunit --configuration phpunit.xml
  - vendor/bin/behat app/tests/acceptance/Category.feature